# Spis Komend:
#
#  > Administracyjne:
#
#  > Dla graczy:
#   /sklepzakille (otwiera gui z sklepem)
#
# Konfiguracja bazy danych
database:
  url: jdbc:mysql://localhost:3306/test
  user: root
  password: ''
# Wiadomosci
messages:
  not_enough_kills: '#cc0000Nie posiadasz wystarczającej liczby zabójstw!#ff2424'
  purchase_success: '#27ff24Pomyślnie dokonano zakupu!#69ff66'
# Konfiguracja sklepu
shop:
  title: '#f62828Sklep za Kille#d04e4e'
  size: 27
  lore:
    - ''
    - '&7Cena: &e%price%'
    - '&bKliknij &9PRAWYM &baby kupic!'
  ui_elements:
    '22':
      type: ENDER_CHEST
      name: '#cc0000Twoje Zabójstwa#ff2424'
      lore:
        - '#27ff24Obecnie posiadasz#27ff24 &c%your_kills% #27ff24zabójstw!#27ff24'
shop-items:
  '11':
    itemstack:
      ==: org.bukkit.inventory.ItemStack
      v: 3578
      type: DIRT
    price: 11
