name: KillShop
version: 1.0
main: org.r3p.repkillshop.KillShopPlugin
api-version: 1.20
commands:
  shopadmin:
    description: Admin command to manage the shop
    usage: /shopadmin <add> <slot> <price>
  sklepzakille:
    description: Command to open the shop
    usage: /sklepzakiller
permissions:
  killshop.admin:
    description: Allows admin to add items to the shop
    default: op