name: KillShop
version: 1.0
main: org.r3p.repkillshop.KillShopPlugin
api-version: 1.18
commands:
  killshopadmin:
    description: Admin command to manage the shop
    usage: /killshopadmin <additem | givekills | clearkills | removekills | reload | removeitem>
  sklepzakille:
    description: Command to open the shop
    usage: /sklepzakille
permissions:
  killshop.admin:
    description: Allows admin to add items to the shop
    default: op
